#!/bin/bash
set -e

# Note: In Maven, the build lifecycle is sequential.
# Running a later phase (like 'mvn install') will automatically execute all prior phases
# (validate, compile, test, package, verify).
# We are writing them out explicitly here just to showcase each individual step.

echo "Starting Maven Build Lifecycle Showcase"

echo "Phase 0: Clean"
# Removes all files generated by the previous build (e.g., the target/ directory).
mvn clean

echo "Phase 1: Validate"
# Verifies that the project is correct and all necessary information is available.
mvn validate

echo "Phase 2: Compile"
# Compiles the source code of the project into bytecode.
mvn compile

echo "Phase 3: Test (and generate JaCoCo coverage)"
# Executes unit tests using a suitable framework (e.g., JUnit).
mvn test
start ./target/site/jacoco/index.html

echo "Phase 4: Package"
# Takes the compiled code and bundles it into its distributable format, such as a JAR.
mvn package

echo "Phase 5: Verify"
# Runs checks on the results of integration tests to ensure quality criteria are met.
mvn verify

echo "Phase 6: Install"
# Places the generated package into the local repository (.m2 folder).
mvn install

echo "Phase 7: Deploy"
# Copies the final package to a remote repository for sharing.
# Commented out: No explicit command is executed here because it requires <distributionManagement>
# to be configured in pom.xml to define the target remote repository.
# mvn deploy

echo "Phase 8: Create Native Application Image (Extra CI Step)"

# Extract project properties dynamically using Maven
ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
APP_NAME=$(mvn help:evaluate -Dexpression=app.name -q -DforceStdout)
MAIN_CLASS=$(mvn help:evaluate -Dexpression=exec.mainClass -q -DforceStdout)

JAR_FILE="${ARTIFACT_ID}-${VERSION}.jar"

mkdir -p target/jpackage-input
cp "target/${JAR_FILE}" target/jpackage-input/
jpackage --type app-image --name "${APP_NAME}" --input target/jpackage-input/ --main-jar "${JAR_FILE}" --dest target/native-image --win-console

echo "Build complete! JaCoCo report is available at target/site/jacoco/index.html"
echo "Native application image is available at target/native-image/${APP_NAME}"