$ErrorActionPreference = "Stop"

# Note: In Maven, the build lifecycle is sequential.
# Running a later phase (like 'mvn install') will automatically execute all prior phases
# (validate, compile, test, package, verify).
# We are writing them out explicitly here just to showcase each individual step.

Write-Host "Starting Maven Build Lifecycle Showcase"

Write-Host "Phase 0: Clean"
# Removes all files generated by the previous build (e.g., the target/ directory).
mvn clean

Write-Host "Phase 1: Validate"
# Verifies that the project is correct and all necessary information is available.
mvn validate

Write-Host "Phase 2: Compile"
# Compiles the source code of the project into bytecode.
mvn compile

Write-Host "Phase 3: Test (and generate JaCoCo coverage)"
# Executes unit tests using a suitable framework (e.g., JUnit).
mvn test

Write-Host "Phase 4: Package"
# Takes the compiled code and bundles it into its distributable format, such as a JAR.
mvn package

Write-Host "Phase 5: Verify"
# Runs checks on the results of integration tests to ensure quality criteria are met.
mvn verify

Write-Host "Phase 6: Install"
# Places the generated package into the local repository (.m2 folder).
mvn install

Write-Host "Phase 7: Deploy"
# Copies the final package to a remote repository for sharing.
# Commented out: No explicit command is executed here because it requires <distributionManagement>
# to be configured in pom.xml to define the target remote repository.
# mvn deploy

Write-Host "Phase 8: Create Native Application Image (Extra CI Step)"

# Extract project properties dynamically using Maven
$artifactId = mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout
$version = mvn help:evaluate -Dexpression=project.version -q -DforceStdout
$appName = mvn help:evaluate -Dexpression=app.name -q -DforceStdout
$mainClass = mvn help:evaluate -Dexpression=exec.mainClass -q -DforceStdout

$jarFile = "${artifactId}-${version}.jar"

New-Item -ItemType Directory -Force -Path target/jpackage-input | Out-Null
Copy-Item "target/$jarFile" target/jpackage-input/
jpackage --type app-image --name $appName --input target/jpackage-input/ --main-jar $jarFile --dest target/native-image --win-console

Write-Host "Build complete! JaCoCo report is available at target/site/jacoco/index.html"
Write-Host "Native application image is available at target/native-image/$appName"