/*
 * This source file was generated by the Gradle 'init' task
 */
package sns.blog;

public class App {
  /**
   * Default greeting method generated by Gradle init. Preserved for template consistency.
   *
   * @return a greeting string.
   */
  public String getGreeting() {
    return "Hello World!";
  }

  /**
   * Main entry point for the SNS Blog Backend wrapper. Delegates execution to either the Javalin or
   * Spring Boot implementation based on the provided command-line argument.
   *
   * @param args Command line arguments. args[0] should be 'javalin' (1) or 'spring' (2).
   * @throws Exception if server startup fails.
   */
  public static void main(String[] args) throws Exception {
    /* [DYNAMIC BACKEND SELECTION] */
    /*
     * The wrapper logic replaces the default Gradle template execution.
     * Previous Implementation (Gradle default):
     * System.out.println(new App().getGreeting());
     */

    if (args.length == 0) {
      System.err.println(
          "Please provide a backend to run as an argument: 'javalin' (or '1') or 'spring' (or '2').");
      System.exit(1);
    }

    String choice = args[0].toLowerCase();

    /* [ROUTING TO TARGET IMPLEMENTATION] */
    if ("1".equals(choice) || "javalin".equals(choice)) {
      System.out.println("Starting Javalin server...");
      sns.blog.javalin.Main.main(args);
    } else if ("2".equals(choice) || "spring".equals(choice)) {
      System.out.println("Starting Spring Boot server...");
      sns.blog.spring.SocialMediaApp.main(args);
    } else {
      System.err.println("Invalid choice: " + choice + ". Exiting.");
      System.exit(1);
    }
  }
}
