/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    /*
     * [Past version]
     * id("org.springframework.boot") version "2.5.5"                   // Spring Boot
     * id("io.spring.dependency-management") version "1.0.11.RELEASE"   // SB dependency BOM
     *
     * Upgraded for Java 21 and Jakarta EE 10.
     * Spring Boot is now 3.3.0.
     * Dependency management plugin is now 1.1.5.
     */
    id("org.springframework.boot") version "3.3.0"              // Spring Boot
    id("io.spring.dependency-management") version "1.1.5"       // SB dependency BOM

    /*
     * [Ylint]
     * Applies sns.blog.lint-conventions from buildSrc (Spotless + Checkstyle).
     */
    id("sns.blog.lint-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    /*
     * [Unit Tests]
     *
     * JUnit 5 (Jupiter) for new tests.
     * Vintage engine runs legacy JUnit 4 suite from Maven.
     */
    testImplementation(libs.junit.jupiter)                              // JUnit Jupiter
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")       // JUnit Platform
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:5.10.2")    // JUnit Vintage
    testImplementation("junit:junit:4.13.2")                            // JUnit 4

    /*
     * [Framework]
     *
     * Spring Boot starters for JPA, web, and integration tests.
     * Coexists with Javalin 7 on Jakarta EE 10 without forced overrides.
     */
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")  // Spring Data JPA
    implementation("org.springframework.boot:spring-boot-starter-web")       // Spring Web
    testImplementation("org.springframework.boot:spring-boot-starter-test")  // Spring Boot Test

    /*
     * [Past version]
     * implementation("io.javalin:javalin:5.0.1")               // Javalin
     *
     * Upgraded to 7.2.2 for Jetty 12 native stack.
     */
    implementation("io.javalin:javalin:7.2.2")                  // Javalin

    /*
     * [Past version]
     * implementation("com.h2database:h2:2.1.214")              // H2 database
     *
     * Upgraded to 2.2.224.
     */
    implementation("com.h2database:h2:2.2.224")                 // H2 database

    /*
     * [Past version]
     * testImplementation("org.mockito:mockito-core:4.9.0")     // Mockito
     *
     * Upgraded to 5.11.0.
     */
    testImplementation("org.mockito:mockito-core:5.11.0")       // Mockito

    /*
     * [Past version - removed]
     * implementation("org.slf4j:slf4j-simple:1.7.36")                              // Logging
     * implementation("com.fasterxml.jackson.core:jackson-databind:2.14.0-rc1")     // JSON
     *
     * Dropped after Spring Boot 3 upgrade.
     * Logback now comes from Spring Boot starters.
     * Jackson is managed by the Spring Boot BOM.
     */
}

java {
    /*
     * [Past version]
     * languageVersion = JavaLanguageVersion.of(11)             // Java toolchain
     *
     * Upgraded to 21 as the primary target platform.
     */
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)            // Java toolchain
    }
}

application {
    // Define the main class for the application.
    mainClass = "sns.blog.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
