package sns.blog.javalin.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This is a class that models an Account.
 *
 * <p>DO NOT CHANGE ANYTHING IN THIS CLASS
 */
public class Account {
  /** An id for this Account which will be automatically generated by the database. */
  @JsonProperty("account_id")
  public int accountId;

  /** A username for this Account (must be unique and not blank) */
  @JsonProperty("username")
  public String username;

  /** A password for this account (must be over 4 characters) */
  @JsonProperty("password")
  public String password;

  /**
   * A default, no-args constructor, as well as correctly formatted getters and setters, are needed
   * for Jackson Objectmapper to work.
   */
  public Account() {}

  /**
   * When posting a new Account, the id can be generated by the database. In that case, a
   * constructor without accountId is needed.
   *
   * @param username
   * @param password
   */
  public Account(String username, String password) {
    this.username = username;
    this.password = password;
  }

  /**
   * Whem retrieving an Account from the database, all fields will be needed. In that case, a
   * constructor with all fields is needed.
   *
   * @param accountId
   * @param username
   * @param password
   */
  public Account(int accountId, String username, String password) {
    this.accountId = accountId;
    this.username = username;
    this.password = password;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @return accountId
   */
  public int getAccountId() {
    return accountId;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @param accountId
   */
  public void setAccountId(int accountId) {
    this.accountId = accountId;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @return username
   */
  public String getUsername() {
    return username;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @param username
   */
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @return password
   */
  public String getPassword() {
    return password;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @param password
   */
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * Overriding the default equals() method adds functionality to tell when two objects are
   * identical, allowing Assert.assertEquals and List.contains to function.
   *
   * @param o the other object.
   * @return true if o is equal to this object.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    Account account = (Account) o;
    return accountId == account.accountId
        && username.equals(account.username)
        && password.equals(account.password);
  }

  /**
   * Overriding the default toString() method allows for easy debugging.
   *
   * @return a String representation of this class.
   */
  @Override
  public String toString() {
    return "Account{"
        + "accountId="
        + accountId
        + ", username='"
        + username
        + '\''
        + ", password='"
        + password
        + '\''
        + '}';
  }
}
