package sns.blog.javalin.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This is a class that models a Message.
 *
 * <p>DO NOT CHANGE ANYTHING IN THIS CLASS!
 */
public class Message {
  /** An id for this message which will be automatically generated by the database. */
  @JsonProperty("message_id")
  public int messageId;

  /**
   * The id for the user who has posted this message. We will assume that this is provided by the
   * front-end of this application.
   */
  @JsonProperty("posted_by")
  public int postedBy;

  /**
   * The text for this message- eg "this is my first post!". Must be not blank and under 255
   * characters
   */
  @JsonProperty("message_text")
  public String messageText;

  /**
   * The epoch time when this tweet was posted (number of seconds since Jan 1, 1970). Longs are
   * large enough to store this number. We will assume that this number is provided by the front-end
   * of this application.
   */
  @JsonProperty("time_posted_epoch")
  public long timePostedEpoch;

  /**
   * A default, no-args constructor, as well as correctly formatted getters and setters, are needed
   * for Jackson Objectmapper to work.
   */
  public Message() {}

  /**
   * When posting a new message, the id can be generated by the database. In that case, a
   * constructor without messageId is needed.
   *
   * @param postedBy
   * @param messageText
   * @param timePostedEpoch
   */
  public Message(int postedBy, String messageText, long timePostedEpoch) {
    this.postedBy = postedBy;
    this.messageText = messageText;
    this.timePostedEpoch = timePostedEpoch;
  }

  /**
   * Whem retrieving a message from the database, all fields will be needed. In that case, a
   * constructor with all fields is needed.
   *
   * @param messageId
   * @param postedBy
   * @param messageText
   * @param timePostedEpoch
   */
  public Message(int messageId, int postedBy, String messageText, long timePostedEpoch) {
    this.messageId = messageId;
    this.postedBy = postedBy;
    this.messageText = messageText;
    this.timePostedEpoch = timePostedEpoch;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @return messageId
   */
  public int getMessageId() {
    return messageId;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @param messageId
   */
  public void setMessageId(int messageId) {
    this.messageId = messageId;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @return postedBy
   */
  public int getPostedBy() {
    return postedBy;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @param postedBy
   */
  public void setPostedBy(int postedBy) {
    this.postedBy = postedBy;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @return messageText
   */
  public String getMessageText() {
    return messageText;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @param messageText
   */
  public void setMessageText(String messageText) {
    this.messageText = messageText;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @return timePostedEpoch
   */
  public long getTimePostedEpoch() {
    return timePostedEpoch;
  }

  /**
   * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use
   * them as well.
   *
   * @param timePostedEpoch
   */
  public void setTimePostedEpoch(long timePostedEpoch) {
    this.timePostedEpoch = timePostedEpoch;
  }

  /**
   * Overriding the default equals() method adds functionality to tell when two objects are
   * identical, allowing Assert.assertEquals and List.contains to function.
   *
   * @param o the other object.
   * @return true if o is equal to this object.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    Message message = (Message) o;
    return messageId == message.messageId
        && postedBy == message.postedBy
        && timePostedEpoch == message.timePostedEpoch
        && messageText.equals(message.messageText);
  }

  /**
   * Overriding the default toString() method allows for easy debugging.
   *
   * @return a String representation of this class.
   */
  @Override
  public String toString() {
    return "Message{"
        + "messageId="
        + messageId
        + ", postedBy="
        + postedBy
        + ", messageText='"
        + messageText
        + '\''
        + ", timePostedEpoch="
        + timePostedEpoch
        + '}';
  }
}
